"""
One-shot i7 node setup:
  - Initialize git repo from existing files OR clone fresh
  - Set PAT-authenticated remote so future git pulls work
  - Set up venv + core deps
  - Write .env with EARTHDATA_TOKEN + GITHUB_PAT
"""
import paramiko
import sys
from pathlib import Path

HOST = "10.0.0.56"
USER = "cesarops"
PASS = "cesarops"

# Load local .env for keys to propagate
def load_env(p):
    env = {}
    try:
        for line in Path(p).read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                env[k.strip()] = v.strip()
    except Exception:
        pass
    return env

local_env = load_env(Path(__file__).parent.parent / ".env")
PAT = local_env.get("GITHUB_PAT", "")
EARTHDATA = local_env.get("EARTHDATA_TOKEN", "")
OPENAI_KEY = local_env.get("OPENAI_API_KEY", "")

if not PAT:
    print("[ERROR] GITHUB_PAT not found in .env — cannot authenticate to private repo")
    sys.exit(1)

REPO_URL = f"https://festeraeb:{PAT}@github.com/festeraeb/wreckhunter2000.git"
BRANCH = "wreckhuntertools"
REPO_DIR = "~/wreckhunter2000-1"

def run(ssh, cmd, timeout=60, quiet=False):
    _, stdout, stderr = ssh.exec_command(cmd, timeout=timeout)
    out = stdout.read().decode(errors="replace").strip()
    err = stderr.read().decode(errors="replace").strip()
    combined = out or err
    if not quiet:
        print(f"  => {combined[:300]}")
    return combined

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
print(f"Connecting to {HOST} ...")
client.connect(HOST, username=USER, password=PASS, timeout=10)
print(f"[+] Connected to {HOST} (i7 node)")

# ── 1. Git setup ──────────────────────────────────────────────────────────────
print("\n[1/4] Setting up git repo ...")
result = run(client, f"ls {REPO_DIR}/.git 2>/dev/null && echo HAS_GIT || echo NO_GIT", quiet=True)
if "NO_GIT" in result:
    print("      No .git dir — initializing git repo in existing directory")
    run(client, f"cd {REPO_DIR} && git init -b {BRANCH}")
    run(client, f"cd {REPO_DIR} && git remote add origin '{REPO_URL}'")
    run(client, f"cd {REPO_DIR} && git fetch origin {BRANCH} --depth=1 2>&1 | tail -5", timeout=120)
    run(client, f"cd {REPO_DIR} && git reset --hard FETCH_HEAD 2>&1 | tail -3")
else:
    print("      .git exists — updating remote URL and pulling latest")
    run(client, f"cd {REPO_DIR} && git remote set-url origin '{REPO_URL}'")
    run(client, f"cd {REPO_DIR} && git fetch origin {BRANCH} --depth=1 2>&1 | tail -5", timeout=120)
    run(client, f"cd {REPO_DIR} && git reset --hard origin/{BRANCH} 2>&1 | tail -3")

log = run(client, f"cd {REPO_DIR} && git log --oneline -3")
print(f"[+] Git log:\n{log}")

# ── 2. Configure git so future pulls don't need creds ─────────────────────────
print("\n[2/4] Configuring git credential store ...")
run(client, f"cd {REPO_DIR} && git config credential.helper store")
run(client, f"echo 'https://festeraeb:{PAT}@github.com' > ~/.git-credentials && chmod 600 ~/.git-credentials", quiet=True)
print("[+] Credentials stored for future pulls")

# ── 3. Venv + deps ────────────────────────────────────────────────────────────
print("\n[3/4] Setting up Python venv ...")
venv_check = run(client, f"test -d {REPO_DIR}/.venv && echo EXISTS || echo MISSING", quiet=True)
if "MISSING" in venv_check:
    print("      Creating venv ...")
    run(client, f"cd {REPO_DIR} && python3 -m venv .venv", timeout=60)
else:
    print("      Venv already exists")

# Install core scan deps
print("      Installing core deps (numpy, scipy, rasterio, requests, paramiko) ...")
run(client,
    f"cd {REPO_DIR} && .venv/bin/pip install --quiet --upgrade pip && "
    f".venv/bin/pip install --quiet numpy scipy rasterio requests paramiko gdal tqdm 2>&1 | tail -5",
    timeout=300)

# Check GPU deps
gpu_check = run(client, f"{REPO_DIR}/.venv/bin/python -c 'import torch; print(torch.cuda.is_available())' 2>/dev/null || echo NO_TORCH", quiet=True)
if "NO_TORCH" in gpu_check or "False" in gpu_check:
    print("      Installing torch with CUDA support ...")
    run(client,
        f"cd {REPO_DIR} && .venv/bin/pip install --quiet torch --index-url https://download.pytorch.org/whl/cu121 2>&1 | tail -5",
        timeout=600)
else:
    print(f"[+] PyTorch CUDA available: {gpu_check}")

# ── 4. Write .env on i7 ───────────────────────────────────────────────────────
print("\n[4/4] Writing .env on i7 ...")
env_content = f"""# Auto-generated by _i7_setup.py
GITHUB_PAT={PAT}
EARTHDATA_TOKEN={EARTHDATA}
OPENAI_API_KEY={OPENAI_KEY}
PI_HOST=10.0.0.226
PI_USER=pi
XENON_HOST=10.0.0.56
XENON_USER=cesarops
"""
# Write file safely via heredoc
run(client, f"cat > {REPO_DIR}/.env << 'ENVEOF'\n{env_content}\nENVEOF", quiet=True)
run(client, f"chmod 600 {REPO_DIR}/.env", quiet=True)
print("[+] .env written")

# ── Summary ───────────────────────────────────────────────────────────────────
print("\n[+] i7 setup complete. System info:")
run(client, "nvidia-smi --query-gpu=name,memory.total --format=csv,noheader")
run(client, f"cd {REPO_DIR} && .venv/bin/python --version")
run(client, f"df -h / | tail -1")

client.close()
print(f"\n[DONE] i7 is ready. Deploy with:")
print(f"  .\\scripts\\deploy_to_pi.ps1 -Nodes i7")
print(f"  # Then to run scan:")
print(f"  # ssh cesarops@10.0.0.56 'cd ~/wreckhunter2000-1 && .venv/bin/python lake_erie_scan.py'")
