#!/usr/bin/env bash
# =============================================================================
# setup_h97_xeon.sh  —  First-boot setup for ASRock H97 / Xeon E3 node
#
# Hardware: Intel Xeon E3 (integrated Intel HD graphics), 28GB RAM, no PCIe GPU yet
# OS:       Ubuntu 22.04 LTS (fresh install)
# Role:     CESARops queue worker — pulls jobs from Pi API, runs scans CPU-side
#
# Run as the target user (NOT root):
#   bash setup_h97_xeon.sh
#
# When Quadro P1000 is installed later, run:
#   bash scripts/enable_gpu_p1000.sh
# =============================================================================

set -euo pipefail

HOSTNAME_NEW="h97xeon"
CESAROPS_USER="${USER}"
REPO_DIR="$HOME/cesarops-core/wreckhunter2000"
VENV_DIR="$HOME/.venv/cesarops"
BRANCH="wreckhuntertools"
REPO_URL="https://github.com/festeraeb/wreckhunter2000.git"
GITHUB_PAT="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"
TAILSCALE_AUTH_KEY="tskey-auth-k6e1Amtx7721CNTRL-usfsHFSTo3CauhckA7WY3CUSbrB6cUAu"
PI_API_URL="http://100.127.66.32:8099"

echo "============================================================"
echo " CESARops H97/Xeon Node Bootstrap"
echo " Host: $HOSTNAME_NEW  User: $CESAROPS_USER"
echo "============================================================"
echo ""

# ── [1/9] Set hostname ───────────────────────────────────────────────────────
echo "[1/9] Setting hostname to $HOSTNAME_NEW..."
sudo hostnamectl set-hostname "$HOSTNAME_NEW"
grep -q "$HOSTNAME_NEW" /etc/hosts || echo "127.0.1.1 $HOSTNAME_NEW" | sudo tee -a /etc/hosts
echo "  ✓ hostname = $HOSTNAME_NEW"

# ── [2/9] System packages ────────────────────────────────────────────────────
echo "[2/9] Installing system packages..."
sudo apt-get update -qq
sudo apt-get install -y --no-install-recommends \
    git curl wget unzip htop tmux vim \
    python3.11 python3.11-venv python3.11-dev python3-pip \
    build-essential pkg-config libssl-dev \
    libgdal-dev gdal-bin \
    libproj-dev proj-data proj-bin \
    libgeos-dev \
    intel-opencl-icd ocl-icd-opencl-dev clinfo \
    libhdf5-dev netcdf-bin libnetcdf-dev \
    ffmpeg libsm6 libxext6 \
    openssh-server ufw \
    2>/dev/null
echo "  ✓ System packages installed"

# Intel integrated GPU OpenCL
if clinfo 2>/dev/null | grep -q "Intel"; then
    echo "  ✓ Intel OpenCL device detected"
else
    echo "  ⚠ Intel OpenCL not yet visible (may need reboot)"
fi

# ── [3/9] Tailscale ──────────────────────────────────────────────────────────
echo "[3/9] Installing Tailscale..."
if ! command -v tailscale &>/dev/null; then
    curl -fsSL https://tailscale.com/install.sh | sh
fi
sudo tailscale up --authkey="$TAILSCALE_AUTH_KEY" --hostname="$HOSTNAME_NEW" --accept-routes
TAILSCALE_IP=$(tailscale ip -4 2>/dev/null || echo "pending")
echo "  ✓ Tailscale up — IP: $TAILSCALE_IP"

# ── [4/9] SSH keys ───────────────────────────────────────────────────────────
echo "[4/9] Configuring SSH..."
mkdir -p ~/.ssh && chmod 700 ~/.ssh
# Allow incoming SSH
sudo ufw allow OpenSSH || true
sudo ufw --force enable || true
# If you want to paste the laptop pubkey in manually, do:
#   echo "ssh-ed25519 AAAA..." >> ~/.ssh/authorized_keys
# The key is on the laptop at C:\Users\thomf\.ssh\id_ed25519.pub
echo "  ✓ SSH configured (add laptop pubkey to ~/.ssh/authorized_keys if needed)"

# ── [5/9] Clone repo ─────────────────────────────────────────────────────────
echo "[5/9] Cloning wreckhunter repo..."
AUTHED_URL="${REPO_URL/https:\/\//https://${GITHUB_PAT}@}"
mkdir -p "$(dirname "$REPO_DIR")"
if [[ -d "$REPO_DIR/.git" ]]; then
    echo "  Repo already cloned — pulling latest..."
    git -C "$REPO_DIR" remote set-url origin "$AUTHED_URL"
    git -C "$REPO_DIR" fetch origin
    git -C "$REPO_DIR" checkout "$BRANCH"
    git -C "$REPO_DIR" pull origin "$BRANCH"
    git -C "$REPO_DIR" remote set-url origin "$REPO_URL"
else
    git clone -b "$BRANCH" "$AUTHED_URL" "$REPO_DIR"
    git -C "$REPO_DIR" remote set-url origin "$REPO_URL"
fi
echo "  ✓ Repo at $REPO_DIR  (branch: $BRANCH)"

# ── [6/9] Python venv + packages ────────────────────────────────────────────
echo "[6/9] Creating Python venv and installing packages..."
python3.11 -m venv "$VENV_DIR"
"$VENV_DIR/bin/pip" install --upgrade pip wheel setuptools -q
"$VENV_DIR/bin/pip" install -r "$REPO_DIR/requirements.txt" -q
echo "  ✓ venv at $VENV_DIR"
echo "  ✓ CPU-only packages installed (no CUDA. Run enable_gpu_p1000.sh after card install)"

# ── [7/9] Write .env ─────────────────────────────────────────────────────────
echo "[7/9] Writing .env..."
cat > "$REPO_DIR/.env" << ENVEOF
# CESARops H97/Xeon node .env — generated by setup_h97_xeon.sh

QWEN_API_KEY=local
QWEN_MODEL=qwen2.5-coder-1.5b-instruct-q6_k
QWEN_BASE_URL=http://localhost:5001/v1

EARTHDATA_USERNAME=cesarops.com
EARTHDATA_PASSWORD=@Juliek01241973
EARTHDATA_TOKEN=eyJ0eXAiOiJKV1QiLCJvcmlnaW4iOiJFYXJ0aGRhdGEgTG9naW4iLCJzaWciOiJlZGxqd3RwdWJrZXlfb3BzIiwiYWxnIjoiUlMyNTYifQ.eyJ0eXBlIjoiVXNlciIsInVpZCI6ImNlc2Fyb3BzLmNvbSIsImV4cCI6MTc4MDc2OTc0NSwiaWF0IjoxNzc1NTg1NzQ1LCJpc3MiOiJodHRwczovL3Vycy5lYXJ0aGRhdGEubmFzYS5nb3YiLCJpZGVudGl0eV9wcm92aWRlciI6ImVkbF9vcHMiLCJhY3IiOiJlZGwiLCJhc3N1cmFuY2VfbGV2ZWwiOjN9.Gcnpvqk16FkSjLFncAUe1OsR-wh_v3ChaZ3zVDxwCT16MI94hqmxKgz9C8ZNobRSFEI1eOpbPIseg5FAyI1YZjCZsZW1dgnzbkNKbVjI8Ibqf5pROsWGk1s5hsUY4qmsa5nVYFxHyxH5NKEMuIKmXo8QQbWkysIAf8soSKaG18SoFoZfLSkzn7NkdrcYu7jzOWtmXqSUSAiQWTrD7q0uUFF2W9Ic8FDltuIKZYPV8FlzHuDP4Z5TNp7wxePz6LMciTpxJsEw1e9G_J2S_eZINNot828VKL3PAWviig3qJ0p4SI3tVPKOhGcbHyVUuMUrsfqFW9CrEQSYggDZ5L2n2g

GITHUB_PAT=${GITHUB_PAT}

PI_HOST=10.0.0.226
PI_TAILSCALE=100.127.66.32
PI_USER=pi
PI_PASS=admin
PI_API_URL=${PI_API_URL}

I7_HOST=10.0.0.56
I7_TAILSCALE=100.85.138.4
I7_USER=cesarops
I7_PASS=cesarops
I7_TPU_PORT=5001

TAILSCALE_AUTH_KEY=${TAILSCALE_AUTH_KEY}
TAILSCALE_API_KEY=tskey-api-kfz9oz2WeF11CNTRL-s3wTNGQbCoMaxukj6u3ZoMrXMoFMSXQrQ
TAILSCALE_TAILNET=-

IONOS_SFTP_HOST=access-5019147877.webspace-host.com
IONOS_SFTP_USER=a1268970
IONOS_SFTP_PASS=@Juliek01241973
IONOS_SFTP_PORT=22

# ── This node capabilities ────────────────────────────────────────
NODE_NAME=h97xeon
NODE_HAS_GPU=false
NODE_GPU=IntelHD_integrated
NODE_HAS_CUDA=false
NODE_HAS_TPU=false
NODE_VRAM_GB=0
NODE_RAM_GB=28
NODE_TRAIN_IDLE=false
ENVEOF
chmod 600 "$REPO_DIR/.env"
echo "  ✓ .env written"

# ── [8/9] Systemd queue worker service ──────────────────────────────────────
echo "[8/9] Installing queue_worker systemd service..."
sudo tee /etc/systemd/system/cesarops-worker.service > /dev/null << SVCEOF
[Unit]
Description=CESARops Queue Worker (h97xeon)
After=network-online.target tailscaled.service
Wants=network-online.target

[Service]
Type=simple
User=${CESAROPS_USER}
WorkingDirectory=${REPO_DIR}
EnvironmentFile=${REPO_DIR}/.env
ExecStart=${VENV_DIR}/bin/python queue_worker.py --target h97xeon --workers 4
Restart=on-failure
RestartSec=15
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
SVCEOF

sudo systemctl daemon-reload
sudo systemctl enable cesarops-worker.service
echo "  ✓ Service installed and enabled (starts on boot)"
echo "  Start now:  sudo systemctl start cesarops-worker"
echo "  Logs:       journalctl -u cesarops-worker -f"

# ── [9/9] Reboot reminder ────────────────────────────────────────────────────
echo ""
echo "============================================================"
echo " SETUP COMPLETE"
echo "============================================================"
echo ""
echo " Node:          $HOSTNAME_NEW"
echo " Repo:          $REPO_DIR"
echo " Venv:          $VENV_DIR"
echo " Tailscale IP:  $TAILSCALE_IP"
echo " Worker:        cesarops-worker.service (4 CPU workers)"
echo ""
echo " GPU status:    Intel HD integrated (OpenCL only, no CUDA)"
echo ""
echo " NEXT STEPS:"
echo "   1. Verify Tailscale:  tailscale status"
echo "   2. Start worker:      sudo systemctl start cesarops-worker"
echo "   3. Watch logs:        journalctl -u cesarops-worker -f"
echo "   4. When P1000 is in:  bash $REPO_DIR/scripts/enable_gpu_p1000.sh"
echo ""
echo " NOTE: A reboot is recommended to fully activate Intel OpenCL."
echo "   sudo reboot"
echo ""
