//! Sovereign Research & Synthesis (SRS) Loop
//!
//! The "Librarian Pattern": The 1.5B model doesn't try to be the expert.
//! It acts as a Research Lead that:
//! 1. Decomposes complex queries into 3-5 sub-queries
//! 2. Fires them in parallel to nautivecs (local) + web oracles (external)
//! 3. Synthesizes findings section by section
//! 4. Stores successful findings back into nautivecs for next time
//!
//! This turns a 1.5B model into an "80B equivalent" by using the internet
//! and local codebase as external RAM rather than trying to memorize everything.

use anyhow::Result;
use serde::{Deserialize, Serialize};

use crate::llm_client::LlmClient;
use crate::steering::SteeringEngine;

// ── Types ────────────────────────────────────────────────────────────────────

/// A research plan generated by the LLM's planning phase
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResearchPlan {
    /// The original complex query
    pub original_query: String,
    /// 3-5 specific sub-queries to investigate
    pub sub_queries: Vec<SubQuery>,
}

/// A single sub-query in the research plan
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubQuery {
    /// The specific question to answer
    pub query: String,
    /// Where to look for the answer
    pub source: QuerySource,
    /// Why this sub-query is needed (for traceability)
    pub rationale: String,
}

/// Where to fetch the answer from
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum QuerySource {
    /// Search the local codebase via nautivecs
    LocalCode,
    /// Search the web via external API (Gemini Flash, Groq, Google)
    WebOracle,
    /// Check the human correction store
    HumanCorrections,
    /// Both local and web (cross-reference)
    CrossReference,
}

/// A finding from one source
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Finding {
    /// Which sub-query this answers
    pub sub_query_index: usize,
    /// The source that provided this finding
    pub source: FindingSource,
    /// The actual content/answer
    pub content: String,
    /// Confidence in this finding (0.0-1.0)
    pub confidence: f32,
    /// Citation (file path, URL, or correction ID)
    pub citation: String,
}

/// Where a finding came from
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum FindingSource {
    /// From nautivecs local code search
    LocalCode { file_path: String, function_name: String },
    /// From web research (external API)
    WebResearch { url: String, api_used: String },
    /// From human correction store
    HumanCorrection { correction_id: String },
}

/// A conflict between sources
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Conflict {
    pub sub_query_index: usize,
    pub source_a: String,
    pub source_b: String,
    pub description: String,
    /// Resolution: which source to trust, or ask human
    pub resolution: ConflictResolution,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ConflictResolution {
    TrustLocalCode,
    TrustCorrection,
    TrustWebResearch,
    AskHuman,
}

/// The complete research result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResearchResult {
    pub plan: ResearchPlan,
    pub findings: Vec<Finding>,
    pub conflicts: Vec<Conflict>,
    pub synthesis: String,
    pub elapsed_ms: u64,
}

// ── Research Engine ──────────────────────────────────────────────────────────

pub struct ResearchEngine {
    llm: LlmClient,
    /// Optional web oracle endpoint (Gemini Flash, Groq, etc.)
    web_oracle_url: Option<String>,
    web_oracle_key: Option<String>,
}

impl ResearchEngine {
    pub fn new(
        llm: LlmClient,
        web_oracle_url: Option<String>,
        web_oracle_key: Option<String>,
    ) -> Self {
        Self { llm, web_oracle_url, web_oracle_key }
    }

    /// Execute the full SRS loop for a complex query.
    ///
    /// 1. Planning: LLM decomposes query into sub-queries
    /// 2. Parallel Fetch: nautivecs + web oracles simultaneously
    /// 3. Conflict Detection: flag disagreements between sources
    /// 4. Sectional Synthesis: build answer one finding at a time
    pub async fn execute(
        &self,
        query: &str,
        steering: &mut SteeringEngine,
    ) -> Result<ResearchResult> {
        let start = std::time::Instant::now();

        // Phase 1: Planning — LLM decomposes the query
        let plan = self.plan_research(query).await?;
        tracing::info!("SRS: {} sub-queries planned", plan.sub_queries.len());

        // Phase 2: Parallel Fetch
        let findings = self.parallel_fetch(&plan, steering).await?;
        tracing::info!("SRS: {} findings collected", findings.len());

        // Phase 3: Conflict Detection
        let conflicts = self.detect_conflicts(&findings);
        if !conflicts.is_empty() {
            tracing::warn!("SRS: {} conflicts detected", conflicts.len());
        }

        // Phase 4: Sectional Synthesis
        let synthesis = self.synthesize(query, &findings, &conflicts).await?;

        let elapsed_ms = start.elapsed().as_millis() as u64;
        tracing::info!("SRS: complete in {}ms", elapsed_ms);

        Ok(ResearchResult {
            plan,
            findings,
            conflicts,
            synthesis,
            elapsed_ms,
        })
    }

    /// Phase 1: Ask the LLM to decompose the query into sub-queries
    async fn plan_research(&self, query: &str) -> Result<ResearchPlan> {
        let planning_prompt = format!(
            "You are a Research Lead. Break this complex question into 3-5 specific sub-queries.\n\
            For each sub-query, specify:\n\
            - The specific question to answer\n\
            - Where to look: LOCAL_CODE (our codebase), WEB (internet), CORRECTIONS (human feedback), or CROSS_REF (both)\n\
            - Why this sub-query is needed\n\n\
            Respond as JSON array: [{{\"query\": \"...\", \"source\": \"LOCAL_CODE|WEB|CORRECTIONS|CROSS_REF\", \"rationale\": \"...\"}}]\n\n\
            Complex question: {}\n\n\
            Sub-queries:",
            query
        );

        let response = self.llm.steered_completion("", &planning_prompt).await?;

        // Parse the LLM's plan (best-effort JSON extraction)
        let sub_queries = self.parse_plan_response(&response, query);

        Ok(ResearchPlan {
            original_query: query.to_string(),
            sub_queries,
        })
    }

    /// Phase 2: Fire all sub-queries in parallel
    async fn parallel_fetch(
        &self,
        plan: &ResearchPlan,
        steering: &mut SteeringEngine,
    ) -> Result<Vec<Finding>> {
        let mut findings = Vec::new();

        // For now, execute sequentially (parallel requires Arc<Mutex> on steering)
        // TODO: Make steering engine thread-safe for true parallel fetch
        for (idx, sub_query) in plan.sub_queries.iter().enumerate() {
            match sub_query.source {
                QuerySource::LocalCode | QuerySource::CrossReference => {
                    // Query nautivecs
                    let context = steering
                        .build_context(&sub_query.query, None, None)
                        .await?;

                    if context.fragments_used > 0 {
                        findings.push(Finding {
                            sub_query_index: idx,
                            source: FindingSource::LocalCode {
                                file_path: "nautivecs_search".to_string(),
                                function_name: sub_query.query.clone(),
                            },
                            content: context.system_prompt.chars().take(500).collect(),
                            confidence: context.confidence,
                            citation: format!("{} fragments from nautivecs", context.fragments_used),
                        });
                    }
                }
                QuerySource::WebOracle => {
                    // Query external API if configured
                    if let Some(ref url) = self.web_oracle_url {
                        match self.query_web_oracle(&sub_query.query, url).await {
                            Ok(content) => {
                                findings.push(Finding {
                                    sub_query_index: idx,
                                    source: FindingSource::WebResearch {
                                        url: url.clone(),
                                        api_used: "web_oracle".to_string(),
                                    },
                                    content,
                                    confidence: 0.6, // Web results get lower base confidence
                                    citation: url.clone(),
                                });
                            }
                            Err(e) => {
                                tracing::warn!("Web oracle failed for sub-query {}: {}", idx, e);
                            }
                        }
                    }
                }
                QuerySource::HumanCorrections => {
                    // Check correction store (already handled by steering engine)
                    let context = steering
                        .build_context(&sub_query.query, None, None)
                        .await?;

                    if context.corrections_applied > 0 {
                        findings.push(Finding {
                            sub_query_index: idx,
                            source: FindingSource::HumanCorrection {
                                correction_id: "correction_store".to_string(),
                            },
                            content: format!("{} corrections applied", context.corrections_applied),
                            confidence: 1.0, // Human corrections are highest confidence
                            citation: "human_correction_store".to_string(),
                        });
                    }
                }
            }
        }

        Ok(findings)
    }

    /// Phase 3: Detect conflicts between findings
    fn detect_conflicts(&self, findings: &[Finding]) -> Vec<Conflict> {
        let mut conflicts = Vec::new();

        // Group findings by sub-query index
        let mut by_index: std::collections::HashMap<usize, Vec<&Finding>> =
            std::collections::HashMap::new();
        for f in findings {
            by_index.entry(f.sub_query_index).or_default().push(f);
        }

        // Check for conflicts within each sub-query
        for (idx, group) in &by_index {
            if group.len() < 2 {
                continue;
            }

            // Simple conflict detection: if local code and web disagree significantly
            let local = group.iter().find(|f| matches!(f.source, FindingSource::LocalCode { .. }));
            let web = group.iter().find(|f| matches!(f.source, FindingSource::WebResearch { .. }));

            if let (Some(l), Some(w)) = (local, web) {
                // If both exist and confidence differs significantly, flag it
                if (l.confidence - w.confidence).abs() > 0.3 {
                    conflicts.push(Conflict {
                        sub_query_index: *idx,
                        source_a: format!("LocalCode (conf: {:.2})", l.confidence),
                        source_b: format!("WebResearch (conf: {:.2})", w.confidence),
                        description: "Significant confidence gap between local and web sources".to_string(),
                        resolution: ConflictResolution::TrustLocalCode, // Default: trust local
                    });
                }
            }
        }

        conflicts
    }

    /// Phase 4: Synthesize findings into a coherent answer
    async fn synthesize(
        &self,
        original_query: &str,
        findings: &[Finding],
        conflicts: &[Conflict],
    ) -> Result<String> {
        // Build a synthesis prompt with all findings
        let mut findings_text = String::new();
        for (i, f) in findings.iter().enumerate() {
            findings_text.push_str(&format!(
                "\nFinding {} (confidence: {:.2}, source: {}):\n{}\n",
                i + 1,
                f.confidence,
                f.citation,
                &f.content[..f.content.len().min(300)]
            ));
        }

        let conflict_text = if conflicts.is_empty() {
            String::new()
        } else {
            let mut text = String::from("\n[CONFLICTS DETECTED]:\n");
            for c in conflicts {
                text.push_str(&format!("- {} vs {}: {}\n", c.source_a, c.source_b, c.description));
            }
            text
        };

        let synthesis_prompt = format!(
            "Based on the following research findings, provide a concise answer to the original question.\n\
            Cite which finding(s) you used. If there are conflicts, note them.\n\n\
            Original question: {}\n\n\
            Findings:{}\n{}\n\
            Synthesized answer:",
            original_query, findings_text, conflict_text
        );

        self.llm.steered_completion("", &synthesis_prompt).await
    }

    /// Query an external web oracle (Gemini Flash, Groq, etc.)
    async fn query_web_oracle(&self, query: &str, oracle_url: &str) -> Result<String> {
        let http = reqwest::Client::builder()
            .timeout(std::time::Duration::from_secs(10))
            .build()?;

        let payload = serde_json::json!({
            "model": "gemini-2.5-flash",
            "messages": [{
                "role": "user",
                "content": format!(
                    "Summarize in 3 bullets the answer to this technical question. \
                    Only include factual information with sources: {}",
                    query
                )
            }],
            "max_tokens": 200,
            "temperature": 0.3,
        });

        let key = self.web_oracle_key.as_deref().unwrap_or("local");

        let response = http
            .post(&format!("{}/chat/completions", oracle_url))
            .header("Authorization", format!("Bearer {}", key))
            .json(&payload)
            .send()
            .await?;

        if !response.status().is_success() {
            anyhow::bail!("Web oracle returned {}", response.status());
        }

        let body: serde_json::Value = response.json().await?;
        let content = body["choices"][0]["message"]["content"]
            .as_str()
            .unwrap_or("(no response)")
            .to_string();

        Ok(content)
    }

    /// Parse the LLM's planning response into structured sub-queries
    fn parse_plan_response(&self, response: &str, original_query: &str) -> Vec<SubQuery> {
        // Try to parse as JSON array
        if let Ok(parsed) = serde_json::from_str::<Vec<serde_json::Value>>(response) {
            return parsed
                .iter()
                .map(|item| SubQuery {
                    query: item["query"].as_str().unwrap_or("").to_string(),
                    source: match item["source"].as_str().unwrap_or("LOCAL_CODE") {
                        "WEB" => QuerySource::WebOracle,
                        "CORRECTIONS" => QuerySource::HumanCorrections,
                        "CROSS_REF" => QuerySource::CrossReference,
                        _ => QuerySource::LocalCode,
                    },
                    rationale: item["rationale"].as_str().unwrap_or("").to_string(),
                })
                .filter(|sq| !sq.query.is_empty())
                .collect();
        }

        // Fallback: if LLM didn't produce valid JSON, create a simple plan
        tracing::warn!("SRS: LLM plan wasn't valid JSON — using fallback decomposition");
        vec![
            SubQuery {
                query: original_query.to_string(),
                source: QuerySource::LocalCode,
                rationale: "Direct search of local codebase".to_string(),
            },
            SubQuery {
                query: format!("usage examples of {}", original_query),
                source: QuerySource::LocalCode,
                rationale: "Find how this is used in practice".to_string(),
            },
        ]
    }
}
