"""
TOP 10 ALUMINUM CANDIDATES - KML GENERATOR

Creates KML/KMZ file with:
- Top 10 aluminum candidates by magnitude
- Rankings in placemark names
- Pop-up info with score, band, coordinates, classification
- Color-coded by magnitude (red = high, yellow = medium, green = low)
- Includes Andaste coordinates for reference
"""

import json
from pathlib import Path
from datetime import datetime

# ── LOAD TOP 10 CANDIDATES ────────────────────────────────────────────────────

aviation_file = Path('c:/Users/thomf/programming/wreckhunter2000/outputs/aviation_filter/aviation_candidates_with_coords.json')

with open(aviation_file, 'r') as f:
    data = json.load(f)

all_candidates = data.get('candidates', [])

# Sort by magnitude (highest first) and take top 10
top_10 = sorted(all_candidates, key=lambda x: -x['magnitude'])[:10]

# Add Andaste coordinates for reference
andaste_coords = [
    {'name': 'ANDESTE Main Hull (Target #1)', 'lat': 42.4729, 'lon': -87.0970, 'type': 'whaleback', 'magnitude': 'N/A (thermal confirmed)'},
    {'name': 'ANDESTE Broken Section (Target #4)', 'lat': 42.4675, 'lon': -87.0813, 'type': 'whaleback', 'magnitude': 'N/A (thermal confirmed)'},
]

# ── KML GENERATION ────────────────────────────────────────────────────────────

def get_color(magnitude):
    """Get color based on magnitude (red=high, yellow=medium, green=low)."""
    if magnitude >= 1.5:
        return 'ff0000ff'  # Red (high magnitude)
    elif magnitude >= 1.0:
        return 'ff00ffff'  # Yellow (medium)
    else:
        return 'ff00ff00'  # Green (low)

def create_kml():
    """Create KML content with top 10 candidates + Andaste."""
    
    kml = '''<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>Top 10 Aluminum Candidates + Andaste</name>
    <description>
      <![CDATA[
      <h1>WreckHunter2000 - Aluminum Candidate Analysis</h1>
      <p><b>Generated:</b> ''' + datetime.now().strftime("%Y-%m-%d %H:%M:%S") + '''</p>
      <p><b>Method:</b> Sentinel-2 L2A satellite data, aluminum filter (B05/B07/B08 bands)</p>
      <p><b>Top 10:</b> Highest magnitude aluminum signatures</p>
      <p><b>Andaste:</b> Confirmed whaleback wreck (thermal signature, not aluminum)</p>
      <p><b>Color Coding:</b></p>
      <ul>
        <li><span style="color: red;">RED</span> = High magnitude (≥1.5) - Potential heavy aluminum</li>
        <li><span style="color: yellow;">YELLOW</span> = Medium magnitude (1.0-1.5) - Possible debris</li>
        <li><span style="color: green;">GREEN</span> = Low magnitude (<1.0) - Uncertain</li>
        <li><span style="color: blue;">BLUE</span> = Andaste (thermal confirmed, not aluminum)</li>
      </ul>
      ]]>
    </description>
    
    <!-- Styles -->
    <Style id="high_mag">
      <IconStyle>
        <color>ff0000ff</color>
        <scale>1.2</scale>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/paddle/red-circle.png</href>
        </Icon>
      </IconStyle>
    </Style>
    
    <Style id="med_mag">
      <IconStyle>
        <color>ff00ffff</color>
        <scale>1.0</scale>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/paddle/ylw-circle.png</href>
        </Icon>
      </IconStyle>
    </Style>
    
    <Style id="low_mag">
      <IconStyle>
        <color>ff00ff00</color>
        <scale>0.8</scale>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/paddle/grn-circle.png</href>
        </Icon>
      </IconStyle>
    </Style>
    
    <Style id="andaste">
      <IconStyle>
        <color>ffff0000</color>
        <scale>1.5</scale>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/paddle/blu-circle.png</href>
        </Icon>
      </IconStyle>
    </Style>
'''
    
    # Add top 10 candidates
    kml += '\n    <!-- TOP 10 ALUMINUM CANDIDATES -->\n'
    
    for i, candidate in enumerate(top_10, 1):
        mag = candidate['magnitude']
        color_style = 'high_mag' if mag >= 1.5 else ('med_mag' if mag >= 1.0 else 'low_mag')
        
        kml += f'''
    <Placemark>
      <name>#{i} - Aluminum Candidate (Mag {mag:.4f})</name>
      <description>
        <![CDATA[
        <h2>Aluminum Candidate #{i}</h2>
        <table>
          <tr><td><b>Rank:</b></td><td>#{i}</td></tr>
          <tr><td><b>Magnitude:</b></td><td>{mag:.4f}</td></tr>
          <tr><td><b>Band:</b></td><td>{candidate['band']}</td></tr>
          <tr><td><b>Coordinates:</b></td><td>{candidate['lat']:.6f}°N, {candidate['lon']:.6f}°W</td></tr>
          <tr><td><b>Distance from South Haven:</b></td><td>{candidate.get('dist_to_sh_mi', 'N/A')}</td></tr>
          <tr><td><b>Classification:</b></td><td>{'HIGH' if mag >= 1.5 else ('MEDIUM' if mag >= 1.0 else 'LOW')}</td></tr>
        </table>
        <p><i>Generated by WreckHunter2000 - CESARops</i></p>
        ]]>
      </description>
      <styleUrl>#{color_style}</styleUrl>
      <Point>
        <coordinates>{candidate['lon']},{candidate['lat']},0</coordinates>
      </Point>
    </Placemark>
'''
    
    # Add Andaste coordinates
    kml += '\n    <!-- ANDESTE WHALEBACK (THERMAL CONFIRMED) -->\n'
    
    for andaste in andaste_coords:
        kml += f'''
    <Placemark>
      <name>{andaste['name']}</name>
      <description>
        <![CDATA[
        <h2>{andaste['name']}</h2>
        <table>
          <tr><td><b>Type:</b></td><td>Whaleback Freighter (1907)</td></tr>
          <tr><td><b>Coordinates:</b></td><td>{andaste['lat']:.6f}°N, {andaste['lon']:.6f}°W</td></tr>
          <tr><td><b>Thermal Signature:</b></td><td>Z-score -2.80 (persistent 2012-2025)</td></tr>
          <tr><td><b>Classification:</b></td><td>Heavy Steel Mass (Whaleback Hull)</td></tr>
          <tr><td><b>Depth:</b></td><td>~100-200m (330-660ft) - estimate</td></tr>
          <tr><td><b>Status:</b></td><td>✅ THERMAL CONFIRMED</td></tr>
        </table>
        <p><i>Generated by WreckHunter2000 - CESARops</i></p>
        <p><i>Dedicated to Dennis Hadfield (March 2025)</i></p>
        ]]>
      </description>
      <styleUrl>#andaste</styleUrl>
      <Point>
        <coordinates>{andaste['lon']},{andaste['lat']},0</coordinates>
      </Point>
    </Placemark>
'''
    
    # Close KML
    kml += '''
  </Document>
</kml>
'''
    
    return kml

# ── MAIN ──────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print('='*80)
    print('TOP 10 ALUMINUM CANDIDATES + ANDESTE - KML GENERATOR')
    print('='*80)
    print()
    
    # Generate KML
    kml_content = create_kml()
    
    # Save KML
    kml_path = Path('c:/Users/thomf/programming/wreckhunter2000/outputs/top_10_aluminum_andaste.kml')
    with open(kml_path, 'w', encoding='utf-8') as f:
        f.write(kml_content)
    
    print(f'KML saved: {kml_path}')
    print()
    print('TOP 10 ALUMINUM CANDIDATES:')
    for i, c in enumerate(top_10, 1):
        print(f'  #{i}: Mag {c["magnitude"]:.4f} ({c["band"]}) at {c["lat"]:.6f}N, {c["lon"]:.6f}W')
    print()
    print('ANDESTE WHALEBACK:')
    for andaste in andaste_coords:
        print(f'  {andaste["name"]}: {andaste["lat"]:.6f}N, {andaste["lon"]:.6f}W (thermal confirmed)')
    print()
    print('Open in Google Earth to view with pop-ups and color coding.')
    print('='*80)
