//! P1000 Ad-hoc Speed + Accuracy Validator
//!
//! The Quadro P1000 (4GB, cesarops2:5571) runs TinyLlama-1.1B-Q4_K_M as an
//! independent reference. When called, it:
//!
//! 1. Sends the same prompt to both the main engine and the P1000 in parallel
//! 2. Compares the top-N token predictions from each
//! 3. Reports token agreement rate (accuracy proxy) and P1000 t/s (speed baseline)
//!
//! This is intentionally lightweight — it's a canary, not a benchmark suite.
//! Agreement rate > 70% on code tasks = main engine is healthy.
//! P1000 t/s gives a hardware-independent reference point.

use serde::{Deserialize, Serialize};
use std::time::Instant;
use tracing::{info, warn};

/// Result of a single validation run.
#[derive(Debug, Serialize)]
pub struct ValidationResult {
    pub prompt: String,
    /// Tokens generated by the main engine
    pub main_tokens: Vec<String>,
    /// Tokens generated by the P1000 reference
    pub ref_tokens: Vec<String>,
    /// How many of the first N tokens agree (exact match)
    pub agreement_count: usize,
    /// Agreement rate 0.0–1.0
    pub agreement_rate: f32,
    /// P1000 tokens per second
    pub ref_tps: f32,
    /// Main engine tokens per second
    pub main_tps: f32,
    /// Whether the main engine looks healthy
    pub healthy: bool,
    /// Human-readable summary
    pub summary: String,
}

/// Config for the validator.
#[derive(Clone, Debug)]
pub struct ValidatorConfig {
    /// Main engine endpoint (e.g. http://127.0.0.1:5001)
    pub main_endpoint: String,
    /// P1000 reference endpoint (e.g. http://100.102.158.111:5571)
    pub ref_endpoint: String,
    /// Number of tokens to compare
    pub n_tokens: usize,
    /// Agreement threshold below which we flag as unhealthy
    pub min_agreement: f32,
}

impl Default for ValidatorConfig {
    fn default() -> Self {
        Self {
            main_endpoint: "http://127.0.0.1:5001".to_string(),
            ref_endpoint: "http://100.102.158.111:5571".to_string(),
            n_tokens: 8,
            min_agreement: 0.5, // 50% agreement = healthy (different model sizes will diverge)
        }
    }
}

/// Run a validation check. Fires both endpoints in parallel.
pub async fn run_validation(
    config: &ValidatorConfig,
    prompt: &str,
) -> ValidationResult {
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(120))
        .build()
        .unwrap_or_default();

    let n = config.n_tokens;

    // Fire both in parallel
    let main_fut = generate_tokens(&client, &config.main_endpoint, prompt, n);
    let ref_fut  = generate_tokens(&client, &config.ref_endpoint,  prompt, n);

    let (main_result, ref_result) = tokio::join!(main_fut, ref_fut);

    let (main_tokens, main_tps) = main_result.unwrap_or_else(|e| {
        warn!("Main engine validation call failed: {}", e);
        (vec!["[error]".to_string()], 0.0)
    });
    let (ref_tokens, ref_tps) = ref_result.unwrap_or_else(|e| {
        warn!("P1000 reference call failed: {}", e);
        (vec!["[unavailable]".to_string()], 0.0)
    });

    // Compare token-by-token (exact string match)
    let compare_len = main_tokens.len().min(ref_tokens.len()).min(n);
    let agreement_count = main_tokens.iter()
        .zip(ref_tokens.iter())
        .take(compare_len)
        .filter(|(a, b)| a == b)
        .count();

    let agreement_rate = if compare_len > 0 {
        agreement_count as f32 / compare_len as f32
    } else {
        0.0
    };

    let healthy = agreement_rate >= config.min_agreement || ref_tps == 0.0; // if ref unavailable, don't flag

    let summary = format!(
        "Agreement: {}/{} tokens ({:.0}%) | Main: {:.1} t/s | P1000 ref: {:.1} t/s | {}",
        agreement_count,
        compare_len,
        agreement_rate * 100.0,
        main_tps,
        ref_tps,
        if healthy { "✓ HEALTHY" } else { "⚠ LOW AGREEMENT" },
    );

    info!("Validation: {}", summary);

    ValidationResult {
        prompt: prompt[..prompt.len().min(80)].to_string(),
        main_tokens,
        ref_tokens,
        agreement_count,
        agreement_rate,
        ref_tps,
        main_tps,
        healthy,
        summary,
    }
}

/// Call a koboldcpp-compatible endpoint, return (tokens, tps).
async fn generate_tokens(
    client: &reqwest::Client,
    endpoint: &str,
    prompt: &str,
    n: usize,
) -> Result<(Vec<String>, f32), reqwest::Error> {
    let url = format!("{}/v1/completions", endpoint.trim_end_matches('/'));

    let t0 = Instant::now();

    let resp = client
        .post(&url)
        .json(&serde_json::json!({
            "prompt": prompt,
            "max_tokens": n,
            "temperature": 0.0,   // greedy — deterministic for comparison
            "top_p": 1.0,
            "stream": false,
        }))
        .send()
        .await?;

    let elapsed = t0.elapsed().as_secs_f32();
    let body: serde_json::Value = resp.json().await?;

    // Extract generated text
    let text = body["choices"][0]["text"]
        .as_str()
        .unwrap_or("")
        .to_string();

    // Rough token split (whitespace-based — good enough for agreement check)
    let tokens: Vec<String> = text
        .split_whitespace()
        .take(n)
        .map(|s| s.to_lowercase().trim_matches(|c: char| !c.is_alphanumeric()).to_string())
        .filter(|s| !s.is_empty())
        .collect();

    // Estimate t/s from usage field if available, else from elapsed
    let completion_tokens = body["usage"]["completion_tokens"]
        .as_u64()
        .unwrap_or(tokens.len() as u64) as f32;
    let tps = if elapsed > 0.0 { completion_tokens / elapsed } else { 0.0 };

    Ok((tokens, tps))
}

/// Quick health ping — just checks if the endpoint responds.
pub async fn ping(endpoint: &str) -> bool {
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(5))
        .build()
        .unwrap_or_default();

    client
        .get(&format!("{}/v1/models", endpoint.trim_end_matches('/')))
        .send()
        .await
        .map(|r| r.status().is_success())
        .unwrap_or(false)
}

/// Run a quick token-rate benchmark on an endpoint.
/// Sends a fixed prompt and measures t/s over n_tokens.
pub async fn benchmark_tps(endpoint: &str, n_tokens: usize) -> Option<f32> {
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(120))
        .build()
        .unwrap_or_default();

    let (_, tps) = generate_tokens(
        &client,
        endpoint,
        "The quick brown fox jumps over the lazy dog. The capital of France is",
        n_tokens,
    ).await.ok()?;

    Some(tps)
}
